name: Auto push results to GitHub

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Commit and push results
        run: |
          git config --global user.name "dexbot"
          git config --global user.email "bot@dex.ai"
          if [ "$(ls -A data/results/ 2>/dev/null)" ]; then
            git add data/results/*.csv
            git commit -m "Auto: push result files [skip ci]" || echo "Nothing to commit"
            git push origin main
          else
            echo "Brak plików do wypchnięcia"
          fi